# Generated by Django 5.0.3 on 2024-04-02 15:49

import AccountApp.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', AccountApp.managers.UserManager()),
            ],
        ),
    ]
